import type { NewsCategory } from "./news.types";

/**
 * The keyword filter's lexicon — the free filter's whole "judgement".
 *
 * Source: the business spec `lexicon.md` (v2, 26 Sep 2026) and its Python
 * reference `lexicon-proto/lex.py`, copied 1:1 (generated, then reviewed);
 * docs/news/lexicon.md in this repo keeps the rules and the weight bands.
 * The worked examples from that spec are the fixtures in
 * news.keyword-filter.spec.ts — change a weight, re-run them.
 *
 * Terms are ALREADY NORMALISED (see news.text.ts: no tashkeel, ا for أإآ,
 * ه for ة, ي for ى/ئ, و for ؤ, lowercase). A trailing `*` = any word suffix.
 * Arabic terms also match with one attached proclitic (و ف ب ل ك ال وال …).
 *
 * Weight bands: 50–60 Saudi-only entity/rule that changes landlord money or
 * obligations; 35–49 strong topical phrase; 20–34 topical but ambiguous;
 * 5–19 context/modifier. `sa: true` = the term alone proves the story is
 * Saudi — never mark a term other Arab states also use.
 */
export interface LexTerm {
  /** Normalised term; trailing `*` = prefix match. */
  t: string;
  /** Weight (title: full, description only: half). */
  w: number;
  tag?: string;
  /** Proof on its own that the story is Saudi. */
  sa?: boolean;
}

/** Category order = the tie-break order (lexicon.md §3). */
export const LEX_CATEGORY_ORDER: NewsCategory[] = ["regulation", "rental", "finance", "housing", "market", "projects", "other"];

export const LEX_CATEGORIES: Record<NewsCategory, LexTerm[]> = {
  regulation: [
    { t: "الهيئه العامه للعقار", w: 55, tag: "rega", sa: true },
    { t: "هيئه العقار", w: 55, tag: "rega", sa: true },
    { t: "real estate general authority", w: 55, tag: "rega", sa: true },
    { t: "rega", w: 35, tag: "rega" },
    { t: "السجل العقاري", w: 50, tag: "real-estate-registry" },
    { t: "التسجيل العيني", w: 45, tag: "real-estate-registry" },
    { t: "real estate registry", w: 50, tag: "real-estate-registry" },
    { t: "التصرفات العقاريه", w: 45, tag: "rett" },
    { t: "ضريبه التصرفات العقاريه", w: 60, tag: "rett" },
    { t: "rett", w: 50, tag: "rett" },
    { t: "real estate transaction tax", w: 60, tag: "rett" },
    { t: "الاراضي البيضاء", w: 55, tag: "white-land", sa: true },
    { t: "الارض البيضاء", w: 55, tag: "white-land", sa: true },
    { t: "رسوم الاراضي", w: 50, tag: "white-land", sa: true },
    { t: "white land*", w: 55, tag: "white-land", sa: true },
    { t: "العقارات الشاغره", w: 55, tag: "vacant-property-fee", sa: true },
    { t: "vacant real estate", w: 55, tag: "vacant-property-fee" },
    { t: "vacant property", w: 50, tag: "vacant-property-fee" },
    { t: "الوساطه العقاريه", w: 40, tag: "brokerage" },
    { t: "رخصه فال", w: 45, tag: "fal-license", sa: true },
    { t: "نظام الوساطه", w: 45, tag: "brokerage" },
    { t: "البيع على الخارطه", w: 45, tag: "off-plan" },
    { t: "وافي", w: 30, tag: "off-plan", sa: true },
    { t: "off plan", w: 35, tag: "off-plan" },
    { t: "تملك الاجانب", w: 45, tag: "foreign-ownership" },
    { t: "للاجانب", w: 20, tag: "foreign-ownership" },
    { t: "foreign buyers", w: 40, tag: "foreign-ownership" },
    { t: "foreign real estate ownership", w: 45, tag: "foreign-ownership" },
    { t: "تملك غير السعوديين", w: 40, tag: "foreign-ownership" },
    { t: "foreign ownership", w: 30, tag: "foreign-ownership" },
    { t: "non saudi buyers", w: 40, tag: "foreign-ownership", sa: true },
    { t: "ملاك العقارات", w: 30, tag: "owners-associations" },
    { t: "اتحاد الملاك", w: 45, tag: "owners-associations" },
    { t: "ادارة وصيانه", w: 10 },
    { t: "قواعد", w: 10 },
    { t: "تنظم", w: 8 },
    { t: "يعتمد", w: 8 },
    { t: "الوزراء", w: 10 },
    { t: "property registration", w: 45, tag: "real-estate-registry" },
    { t: "الاعلانات العقاريه", w: 35, tag: "brokerage" },
    { t: "وزاره العدل", w: 15, tag: "moj" },
    { t: "الصكوك العقاريه", w: 35, tag: "deeds" },
    { t: "صك*", w: 8 },
    { t: "لايح*", w: 15 },
    { t: "اللايحه التنفيذيه", w: 20 },
    { t: "مسوده", w: 12 },
    { t: "نظام", w: 6 },
    { t: "قرار", w: 8 },
    { t: "مجلس الوزراء", w: 15 },
    { t: "رسوم", w: 12 },
    { t: "غرام*", w: 12 },
    { t: "مخالف*", w: 6 },
    { t: "حصر", w: 10 },
    { t: "مهله", w: 12 },
    { t: "العقوبات", w: 12 },
    { t: "ملاك الاراضي", w: 25, tag: "white-land" },
    { t: "الاراضي الفضاء", w: 35, tag: "white-land" },
    { t: "التوازن العقاري", w: 45, tag: "rcrc-balance", sa: true },
    { t: "real estate balance", w: 45, tag: "rcrc-balance", sa: true },
    { t: "الزام*", w: 10 },
    { t: "استطلاع", w: 6 },
    { t: "regulation*", w: 12 },
    { t: "law", w: 8 },
    { t: "fee*", w: 10 },
    { t: "tax", w: 12 },
  ],
  rental: [
    { t: "منصه ايجار", w: 60, tag: "ejar", sa: true },
    { t: "ejar", w: 55, tag: "ejar", sa: true },
    { t: "تثبيت الايجار*", w: 60, tag: "rent-freeze", sa: true },
    { t: "rent freeze", w: 60, tag: "rent-freeze", sa: true },
    { t: "زياده الايجار*", w: 45, tag: "rent-increase" },
    { t: "العلاقه الايجاريه", w: 50, tag: "tenancy-law" },
    { t: "عقد ايجار*", w: 30, tag: "lease" },
    { t: "عقود الايجار", w: 30, tag: "lease" },
    { t: "عقود ايجار", w: 30, tag: "lease" },
    { t: "ايجار*", w: 20, tag: "rent" },
    { t: "الايجارات السكنيه", w: 45, tag: "residential-rent" },
    { t: "الايجارات التجاريه", w: 40, tag: "commercial-rent" },
    { t: "المستاجر*", w: 25, tag: "tenants" },
    { t: "المؤجر*", w: 30, tag: "landlords" },
    { t: "المستاجرين", w: 25, tag: "tenants" },
    { t: "المالك والمستاجر", w: 40, tag: "tenancy-law" },
    { t: "اخلاء", w: 20, tag: "eviction" },
    { t: "تاجير", w: 12, tag: "rent" },
    { t: "rent", w: 20, tag: "rent" },
    { t: "rents", w: 25, tag: "rent" },
    { t: "rental*", w: 25, tag: "rent" },
    { t: "lease*", w: 15, tag: "lease" },
    { t: "tenant*", w: 25, tag: "tenants" },
    { t: "landlord*", w: 30, tag: "landlords" },
    { t: "rent burden", w: 40, tag: "rent" },
    { t: "ايجار شهري", w: 20, tag: "rent" },
    { t: "الدفع الشهري للايجار", w: 35, tag: "rent" },
  ],
  finance: [
    { t: "صندوق التنميه العقاريه", w: 50, tag: "redf", sa: true },
    { t: "الصندوق العقاري", w: 50, tag: "redf", sa: true },
    { t: "redf", w: 50, tag: "redf", sa: true },
    { t: "التمويل العقاري", w: 45, tag: "mortgage" },
    { t: "الرهن العقاري", w: 40, tag: "mortgage" },
    { t: "mortgage*", w: 40, tag: "mortgage" },
    { t: "home loan*", w: 35, tag: "mortgage" },
    { t: "الشركه السعوديه لاعاده التمويل العقاري", w: 55, tag: "src", sa: true },
    { t: "اعاده التمويل العقاري", w: 50, tag: "src" },
    { t: "saudi real estate refinance", w: 55, tag: "src", sa: true },
    { t: "src", w: 25, tag: "src" },
    { t: "ساما", w: 25, tag: "sama", sa: true },
    { t: "البنك المركزي السعودي", w: 30, tag: "sama" },
    { t: "sama", w: 25, tag: "sama", sa: true },
    { t: "سايبور", w: 25, tag: "saibor", sa: true },
    { t: "saibor", w: 25, tag: "saibor", sa: true },
    { t: "ريت", w: 25, tag: "reit" },
    { t: "reit*", w: 25, tag: "reit" },
    { t: "صناديق الاستثمار العقاري", w: 35, tag: "reit" },
    { t: "صندوق عقاري", w: 25, tag: "reit" },
    { t: "real estate fund", w: 30, tag: "reit" },
    { t: "توزيعات", w: 8 },
    { t: "dividend*", w: 8 },
    { t: "صكوك", w: 12 },
    { t: "sukuk", w: 12 },
  ],
  housing: [
    { t: "الدعم السكني", w: 50, tag: "sakani", sa: true },
    { t: "سكني", w: 35, tag: "sakani" },
    { t: "المسكن الاول", w: 30, tag: "home-ownership" },
    { t: "المسكن", w: 12, tag: "housing" },
    { t: "sakani", w: 45, tag: "sakani", sa: true },
    { t: "برنامج الاسكان", w: 40, tag: "housing-program" },
    { t: "housing program", w: 35, tag: "housing-program" },
    { t: "وزاره البلديات والاسكان", w: 40, tag: "momah", sa: true },
    { t: "البلديات والاسكان", w: 40, tag: "momah", sa: true },
    { t: "وزير البلديات والاسكان", w: 30, tag: "momah", sa: true },
    { t: "وزير الاسكان", w: 25, tag: "momah" },
    { t: "momah", w: 40, tag: "momah", sa: true },
    { t: "ministry of municipalities and housing", w: 40, tag: "momah", sa: true },
    { t: "الشركه الوطنيه للاسكان", w: 45, tag: "nhc", sa: true },
    { t: "national housing company", w: 45, tag: "nhc", sa: true },
    { t: "nhc", w: 35, tag: "nhc" },
    { t: "التملك السكني", w: 40, tag: "home-ownership" },
    { t: "تملك المساكن", w: 40, tag: "home-ownership" },
    { t: "نسبه التملك", w: 40, tag: "home-ownership" },
    { t: "homeownership", w: 35, tag: "home-ownership" },
    { t: "home ownership", w: 35, tag: "home-ownership" },
    { t: "الاسكان التنموي", w: 35, tag: "developmental-housing" },
    { t: "جود الاسكان", w: 20, tag: "developmental-housing" },
    { t: "اسكان", w: 18, tag: "housing" },
    { t: "housing", w: 18, tag: "housing" },
    { t: "وحده سكنيه", w: 20, tag: "housing" },
    { t: "وحدات سكنيه", w: 25, tag: "housing" },
    { t: "مخطط* سكني*", w: 25, tag: "land" },
    { t: "قطعه ارض", w: 15, tag: "land" },
    { t: "قطع اراض*", w: 15, tag: "land" },
    { t: "residential", w: 15, tag: "housing" },
    { t: "السكني*", w: 12, tag: "housing" },
    { t: "مستفيدي*", w: 15, tag: "sakani" },
    { t: "own their home", w: 25, tag: "home-ownership" },
  ],
  market: [
    { t: "مؤشر اسعار العقارات", w: 55, tag: "price-index" },
    { t: "الرقم القياسي لاسعار العقارات", w: 55, tag: "price-index" },
    { t: "real estate price index", w: 55, tag: "price-index" },
    { t: "الصفقات العقاريه", w: 40, tag: "transactions" },
    { t: "صفقات الاسكان", w: 35, tag: "transactions" },
    { t: "صفقات عقاريه", w: 35, tag: "transactions" },
    { t: "real estate transactions", w: 45, tag: "transactions" },
    { t: "property transactions", w: 40, tag: "transactions" },
    { t: "اسعار العقارات", w: 35, tag: "prices" },
    { t: "اسعار الايجارات", w: 40, tag: "rent" },
    { t: "تضخم الايجارات", w: 55, tag: "rent-inflation" },
    { t: "property prices", w: 35, tag: "prices" },
    { t: "home sales", w: 30, tag: "transactions" },
    { t: "تكاليف البناء", w: 45, tag: "construction-costs" },
    { t: "construction costs", w: 45, tag: "construction-costs" },
    { t: "رخص البناء", w: 35, tag: "building-permits" },
    { t: "building permits", w: 35, tag: "building-permits" },
    { t: "الرقم القياسي", w: 15 },
    { t: "المبيعات العقاريه", w: 35, tag: "transactions" },
    { t: "مبيعات العقارات", w: 30, tag: "transactions" },
    { t: "التداولات العقاريه", w: 30, tag: "transactions" },
    { t: "sales", w: 8 },
    { t: "القطاع العقاري", w: 25, tag: "market" },
    { t: "السوق العقاري*", w: 30, tag: "market" },
    { t: "سوق العقار*", w: 30, tag: "market" },
    { t: "real estate market", w: 30, tag: "market" },
    { t: "property market", w: 30, tag: "market" },
    { t: "الهيئه العامه للاحصاء", w: 20, tag: "gastat" },
    { t: "gastat", w: 20, tag: "gastat" },
  ],
  projects: [
    { t: "روشن", w: 30, tag: "roshn", sa: true },
    { t: "roshn", w: 30, tag: "roshn", sa: true },
    { t: "مشروع*", w: 6 },
    { t: "شركه مشتركه", w: 10 },
    { t: "joint venture", w: 10 },
    { t: "نيوم", w: 15, tag: "neom", sa: true },
    { t: "neom", w: 15, tag: "neom", sa: true },
    { t: "الدرعيه", w: 15, tag: "diriyah" },
    { t: "diriyah", w: 15, tag: "diriyah" },
    { t: "المربع الجديد", w: 25, tag: "new-murabba", sa: true },
    { t: "new murabba", w: 25, tag: "new-murabba", sa: true },
    { t: "القديه", w: 12, tag: "qiddiya", sa: true },
    { t: "qiddiya", w: 12, tag: "qiddiya", sa: true },
    { t: "البحر الاحمر", w: 8 },
    { t: "حديقه الملك سلمان", w: 20, tag: "king-salman-park" },
    { t: "مسار", w: 10 },
    { t: "وحده", w: 10 },
    { t: "وحدات", w: 12 },
    { t: "مجتمع* سكني*", w: 25, tag: "development" },
    { t: "homes", w: 12, tag: "housing" },
    { t: "units", w: 10 },
    { t: "development", w: 12, tag: "development" },
    { t: "community", w: 8 },
    { t: "جبل عمر", w: 15 },
    { t: "التطوير العقاري", w: 25, tag: "development" },
    { t: "مطور* عقاري*", w: 25, tag: "development" },
    { t: "مشروع* سكني*", w: 25, tag: "development" },
    { t: "real estate develop*", w: 25, tag: "development" },
    { t: "developer", w: 15, tag: "development" },
    { t: "البنيه التحتيه", w: 8 },
    { t: "مخطط*", w: 8 },
    { t: "تطوير", w: 6 },
    { t: "ابراج", w: 8 },
    { t: "برج*", w: 6 },
  ],
  other: [
    { t: "عقار*", w: 20, tag: "real-estate" },
    { t: "العقاري*", w: 20, tag: "real-estate" },
    { t: "real estate", w: 20, tag: "real-estate" },
    { t: "property", w: 12, tag: "real-estate" },
    { t: "properties", w: 12, tag: "real-estate" },
    { t: "اراض*", w: 10, tag: "land" },
    { t: "ارض", w: 8, tag: "land" },
    { t: "land", w: 8, tag: "land" },
    { t: "مستودع*", w: 8 },
    { t: "مكاتب", w: 6 },
    { t: "office*", w: 5 },
  ],
};

/** Saudi geography: in title or description → +10 (and overrides a foreign marker). */
export const SAUDI_GEO: string[] = [
  "السعوديه", "السعودي", "سعودي*", "المملكه", "الرياض", "جده", "مكه المكرمه", "مكه", "المدينه المنوره",
  "الدمام", "الشرقيه", "المنطقه الشرقيه", "القصيم", "حايل", "عسير", "ابها", "تبوك", "جازان", "نجران",
  "الباحه", "الجوف", "الاحساء", "الطايف", "بريده", "الدرعيه", "ينبع", "الخرج", "saudi*", "ksa", "riyadh",
  "jeddah", "makkah", "mecca", "madinah", "dammam", "khobar", "eastern province", "hail", "qassim", "tabuk",
  "diriyah", "tadawul", "tasi", "تاسي",
];

/** Foreign markers, checked in the TITLE only: without Saudi context → −60. */
export const FOREIGN_GEO: string[] = [
  "مصر", "المصري*", "القاهره", "دبي", "ابوظبي", "الامارات*", "الاماراتي*", "الكويت*", "قطر", "القطري*",
  "البحرين*", "عمان", "سلطنه عمان", "الاردن", "لبنان", "سوريا", "العراق", "تركيا", "المغرب", "تونس",
  "الجزاير", "اليمن", "تعز", "بريطانيا", "لندن", "امريكا", "اميركا", "الامريكي*", "الاميركي*",
  "الولايات المتحده", "اوروبا", "الاوروبي*", "المانيا", "فرنسا", "برشلونه", "اسبانيا", "الصين", "اليابان",
  "كندا", "استراليا", "السويد", "المالديف", "فيتنام", "الهند", "egypt*", "cairo", "dubai", "abu dhabi",
  "uae", "emirat*", "kuwait*", "qatar*", "bahrain*", "oman", "jordan", "lebanon", "syria", "turkey", "uk",
  "london", "britain", "us", "america*", "europe*", "germany", "france", "spain", "china", "japan", "canada",
  "australia", "sweden", "maldives", "vietnam", "india", "nj", "switzerland", "florida", "جبل لبنان",
  "هانوي", "الايجار القديم", "قانون 164", "برلماني", "الرعايه السكنيه", "درهم", "د ك", "الجنيه", "جنيه",
];

/** Negative terms and their penalty points (title or description). */
export const NEGATIVE: Array<[term: string, penalty: number]> = [
  ["للبيع", 60],
  ["للايجار", 45],
  ["for sale", 50],
  ["for rent", 45],
  ["احجز", 40],
  ["احجز الان", 50],
  ["book now", 50],
  ["سارع", 30],
  ["عرض خاص", 45],
  ["خصم", 25],
  ["تخفيض*", 20],
  ["اكتتاب", 0],
  ["مسابقه", 50],
  ["سحب علي", 50],
  ["جوايز", 30],
  ["ريتويت", 50],
  ["giveaway", 50],
  ["win", 20],
  ["عيد مبارك", 60],
  ["كل عام وانتم", 60],
  ["اليوم الوطني", 35],
  ["يوم التاسيس", 35],
  ["رمضان كريم", 60],
  ["جمعه مباركه", 60],
  ["تهنئه", 35],
  ["يهني*", 35],
  ["تعزيه", 60],
  ["national day", 35],
  ["معرض", 15],
  ["تكرم", 40],
  ["خريجي", 40],
  ["بحضور", 20],
  ["ملتقي", 10],
  ["يزور", 25],
  ["زياره", 15],
  ["يدشن مقره", 40],
  ["مقره الجديد", 40],
  ["يفتتح", 10],
  ["يستقبل", 30],
  ["يراس", 20],
  ["يطلع على", 25],
  ["ورشه عمل", 25],
  ["جناح", 25],
  ["نشارك", 25],
  ["جايزه", 20],
  ["award*", 20],
  ["السيره الذاتيه", 60],
  ["معلومات الشركه", 60],
  ["الهاشتاجات", 80],
  ["الوسايط", 60],
  ["مباراه", 50],
  ["الدوري", 50],
  ["كره القدم", 50],
  ["منتخب", 40],
  ["ملاكمه", 50],
  ["بطوله", 30],
  ["match", 30],
  ["league", 40],
  ["football", 40],
  ["soccer", 50],
  ["النفط", 25],
  ["الذهب", 30],
  ["برنت", 30],
  ["crude", 25],
  ["oil", 15],
  ["gold", 25],
  ["bitcoin", 40],
  ["بتكوين", 40],
  ["سعر صرف", 30],
  ["الاسترليني", 40],
  ["الين", 20],
  ["الروبل", 40],
  ["مقذوف", 40],
  ["وفاه", 40],
  ["وفاتان", 40],
  ["اصابه", 25],
  ["اصابات", 25],
  ["مخدرات", 50],
  ["سلاح", 40],
  ["الحوثي*", 40],
  ["هجوم", 20],
  ["attack*", 25],
  ["الطقس", 40],
  ["امطار", 40],
  ["الارصاد", 40],
  ["تداولات المطلعين", 40],
  ["محضر اجتماع", 40],
  ["الجمعيه العموميه", 25],
  ["stock price and chart", 80],
  ["ex dividend", 15],
  ["52 week low*", 30],
  ["all time low*", 25],
  ["lowest since debut", 25],
  ["نصايح", 20],
  ["هل تعلم", 40],
  ["خبير يحذر", 15],
  ["كل ما تريد معرفته", 25],
  ["الابل", 60],
  ["المركبه", 40],
  ["سياره", 40],
  ["السيارات", 40],
];

/**
 * Hard blocks on the normalised title or description → score 0: phone
 * numbers, 9200 numbers, "for sale/rent … <price>", WhatsApp, retweet-to-win.
 * Python-regex sources; `\\b` is made Unicode-aware when compiled (JS's is ASCII-only).
 */
export const BLOCK_RE_SOURCES: string[] = [
  String.raw`(?:\+?966|\b0)5\d{8}\b`,
  String.raw`\b9200\d{5}\b`,
  String.raw`\b05\d\s?\d{3}\s?\d{4}\b`,
  String.raw`(?:للبيع|للايجار|for sale|for rent)\b.*\b\d{3,}`,
  String.raw`واتساب|whatsapp|wa me`,
  String.raw`(?:رتويت|ريتويت|retweet)\s`,
];

/** A figure with a unit in the title → +8. */
export const DATA_RE_SOURCE = String.raw`\d[\d\.,]*\s*(?:وحده|اسره|قطعه|homes?|units?|families|%|مليار|مليون|الف|ريال|قطعه|sar|bn|billion|million|pc)|%\s*\d`;

/** End-of-title patterns of index/entity pages, not articles → score 0. */
export const PAGE_RE_SOURCE = String.raw`(?:الاخبار|الافصاحات|تقارير ارقام|معلومات الشركه|stock price and chart|الوسايط|الهاشتاجات)$`;

/** Wire-service section prefixes («عام / …») dropped from titles before scoring and display. */
export const TITLE_PREFIX_RE = /^\s*(?:عام|اقتصادي|اليوم الوطني|منوعات عالمية|رياضي|ثقافي|سياسي)\s*\/\s*/u;

export const LEX_SCORING = {
  /** Diminishing returns for the 1st, 2nd, 3rd, 4th+ hit (by weight). */
  dim: [1.0, 0.6, 0.4, 0.25],
  dimRest: 0.25,
  descFactor: 0.5,
  saudiBonus: 10,
  foreignPenalty: -60,
  noGeoPenalty: -10,
  dataBonus: 8,
  shortTitleWords: 4,
  shortTitlePenalty: 40,
  relevantMin: 60,
  /** The reference scored the first 400 characters of the description. */
  descMaxChars: 400,
} as const;

